Add smithy-build.json instructions for dependencies
awslabs/smithy-vscode pull request #35
Opened 2022-05-19 21:44 UTC by srchase

This PR adds instructions for specifying `smithy-build.json` for use with the Smithy Language Server.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-19 23:05 UTC, kstich requested changes

2022-05-19 23:05 UTC, kstich commented on README.md
> +* Start authoring your Smithy model. Opening a `*.smithy` file will active the extension.
s/active/activate

2022-05-19 23:05 UTC, kstich commented on README.md
> +* Open VS Code and add a `smithy-build.json` file to the root of your project, specifying any Maven dependencies used by your model, along with the repositories where they can be located.
Cap line length?

2022-05-20 13:40 UTC, srchase commented on README.md
> +* Start authoring your Smithy model. Opening a `*.smithy` file will active the extension.
Fixed in 8aeb801.

2022-05-20 13:40 UTC, srchase commented on README.md
> +* Open VS Code and add a `smithy-build.json` file to the root of your project, specifying any Maven dependencies used by your model, along with the repositories where they can be located.
Fixed all the long lines in 8aeb801.

2022-05-20 15:44 UTC, kstich approved these changes

2022-05-20 15:53 UTC, merged