feat: add root path configuration
awslabs/smithy-vscode pull request #54
Opened 2022-09-17 04:24 UTC by eduardomourar

*Issue #, if available:* N/A

*Description of changes:*

Allow users to customize the root path to be used the Smithy VSCode extension.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-20 21:20 UTC, milesziemer commented on src/extension.ts
>    };
This can all probably be moved to its own top-level function, something like `getClientOptions`, with a return type of `LanguageClientOptions`

2022-09-21 17:36 UTC, milesziemer requested changes

2022-09-21 19:54 UTC, eduardomourar commented on package.json
> +    "vscode-tmgrammar-test": "^0.1.1"
At least bumping the language client package is required for the feature of this PR. Otherwise the root workspace is not passed down correctly.

2022-09-21 19:58 UTC, eduardomourar commented on test-fixtures/suite1/smithy/smithy-build.json
> +    "dependencies": ["software.amazon.smithy:smithy-aws-traits:1.25.0", "software.amazon.smithy:smithy-waiters:1.25.0"],
I wanted to ensure we were testing minimally 2 packages being installed.

2022-09-21 20:00 UTC, eduardomourar commented on package.json
> +    "test-grammar": "npx vscode-tmgrammar-test -g syntaxes/smithy.tmLanguage.json 'tests/grammar/*'",
Yes, I will create a separate PR with all version bumps and these related changes.

2022-09-21 20:17 UTC, eduardomourar commented on src/extension.ts
> +    revealOutputChannelOn: RevealOutputChannelOn.Never,
Done. PR here: https://github.com/awslabs/smithy-vscode/pull/55

2022-09-21 20:29 UTC, eduardomourar commented on package.json
> +    "vscode-tmgrammar-test": "^0.1.1"
I have moved the others to this PR here: https://github.com/awslabs/smithy-vscode/pull/56

2022-09-21 20:31 UTC, eduardomourar commented on test-fixtures/suite3/smithy-build.json
> +    "dependencies": ["software.amazon.smithy:smithy-aws-traits:1.25.0"],
Move to this PR here: https://github.com/awslabs/smithy-vscode/pull/56

2022-09-21 20:31 UTC, eduardomourar commented on test-fixtures/suite1/smithy/smithy-build.json
> +    "dependencies": ["software.amazon.smithy:smithy-aws-traits:1.25.0", "software.amazon.smithy:smithy-waiters:1.25.0"],
Moved

2022-09-21 21:05 UTC, eduardomourar commented on test-fixtures/suite1/.vscode/settings.json
> +}
Done

2022-09-22 14:01 UTC, milesziemer commented
Thank you for separating the PRs, they have been merged. Please rebase and push this branch back up to avoid conflict.

2022-09-22 18:48 UTC, milesziemer approved these changes

2022-09-22 18:50 UTC, merged